Verification Code Endpoints
ScottyLabs/tartanhacks-backend pull request #58
Opened 2022-01-03 03:49 UTC by btwj

Adds endpoints `/auth/discord/verification-code/` and `/user/get-verification-code`

- Right now, if a user doesn't have a verification code or their current code is expired, generates a new one. Should there be another endpoint to force the code to be re-generated?

2022-01-03 03:51 UTC, anudaweerasinghe commented
Resolves #54

2022-01-03 06:19 UTC, anudaweerasinghe commented on src/models/User.ts
> +  this.verificationCode = newCode;
how do we ensure two users don't have the same verification code - probably not worth dealing with.

2022-01-03 06:20 UTC, anudaweerasinghe requested changes

2022-01-03 06:20 UTC, anudaweerasinghe commented on src/routes/auth.ts
> +  "/discord/verification-code",
Let's rename this endpoint to /auth/discord/verify

2022-01-03 06:20 UTC, anudaweerasinghe commented on src/routes/user.ts
> +  "/get-verification-code",
Rename to /user/verification

2022-01-03 16:45 UTC, btwj commented on src/models/User.ts
> +  this.verificationCode = newCode;
I think the chance of collision is pretty small since there are 64^8 codes - if this is a concern, we could make the code longer too

2022-01-04 11:23 UTC, gramliu approved these changes

2022-01-04 12:03 UTC, anudaweerasinghe approved these changes

2022-01-04 12:03 UTC, merged